[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.83.1"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.split1]
  command = "hugo --gc --minify --enableGitInfo"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
